# Generated by Django 4.2.2 on 2023-07-16 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_reviews_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='isVerified',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
