# Generated by Django 4.2.2 on 2023-07-20 04:38

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_product_brand_alter_product_brand_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_for_men',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='is_for_women',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='men_image',
            field=models.ImageField(default='', upload_to=products.models.get_category_image_upload_path),
        ),
        migrations.AddField(
            model_name='category',
            name='women_image',
            field=models.ImageField(default='', upload_to=products.models.get_category_image_upload_path),
        ),
    ]
