# Generated by Django 4.2.2 on 2023-07-20 05:02

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_category_is_for_men_category_is_for_women_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='men_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to=products.models.get_category_image_upload_path),
        ),
        migrations.AlterField(
            model_name='category',
            name='women_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to=products.models.get_category_image_upload_path),
        ),
    ]
