# Generated by Django 4.2.2 on 2023-07-20 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_category_men_image_alter_category_women_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_for',
            field=models.CharField(blank=True, choices=[('Men', 'Men'), ('Women', 'Women'), ('Both', 'Both')], max_length=20, null=True),
        ),
    ]
