# Generated by Django 4.2.2 on 2023-07-20 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_category_is_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='is_for',
            field=models.CharField(blank=True, choices=[('men', 'Men'), ('women', 'Women'), ('both', 'Both')], max_length=20, null=True),
        ),
    ]
