# Generated by Django 4.2.2 on 2023-07-22 14:26

from django.db import migrations, models
import products.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_category_is_for'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billboard',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('billboard_title', models.CharField(max_length=255)),
                ('billboard_image', models.ImageField(default='', upload_to=products.models.get_billboard_image_upload_path)),
                ('billboard_description', models.CharField(max_length=255)),
                ('billboard_url', models.CharField(max_length=255)),
                ('billboard_for', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
