# Generated by Django 4.2.2 on 2023-07-23 04:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_billboard_billboard_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coupon_code', models.CharField(max_length=50)),
                ('is_expired', models.BooleanField(default=False)),
                ('discount_percent', models.IntegerField(default=0)),
                ('minimum_amount', models.ImageField(default=0, upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
