# Generated by Django 4.2.2 on 2023-07-23 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_coupon_minimum_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='coupon_type',
            field=models.CharField(blank=True, choices=[('percentage', 'percentage'), ('flat', 'flat')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='discount_flat',
            field=models.IntegerField(default=0),
        ),
    ]
