# Generated by Django 4.2.2 on 2023-07-23 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_coupon_coupon_type_coupon_discount_flat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='discount_flat',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_percent',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
