# Generated by Django 4.2.2 on 2023-07-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_coupon_discount_flat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='maximum_discount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
