# Generated by Django 4.2.2 on 2023-07-23 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_coupon_maximum_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='coupon_count_peruser',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
