# Generated by Django 4.2.2 on 2023-08-03 03:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_coupon_coupon_count_peruser'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('color_name', models.CharField(blank=True, max_length=55, null=True)),
                ('color_code', models.CharField(blank=True, max_length=55, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
