# Generated by Django 4.2.2 on 2023-07-14 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_address_created_at_alter_address_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='totalRefundAmount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
    ]
