# Generated by Django 4.2.2 on 2023-07-15 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_bank_order_refundbankdetails'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bank',
            options={'verbose_name_plural': 'Bank Details'},
        ),
        migrations.AlterField(
            model_name='bank',
            name='iban',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='swift_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
