# Generated by Django 4.2.2 on 2023-07-24 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_order_couponapplied'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='couponDicount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
    ]
