# Generated by Django 4.2.2 on 2023-07-25 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_order_shippingaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='refundBankDetails',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_bank_details', to='account.bank'),
        ),
    ]
