# Generated by Django 4.2.2 on 2023-07-28 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_testimonial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='review_description',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='testimonial_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
