# Generated by Django 4.2.2 on 2023-08-02 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_returnorder_cancelorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancelorder',
            name='orderItem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cancel_order_item', to='account.orderitem'),
        ),
        migrations.AddField(
            model_name='returnorder',
            name='orderItem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_order_item', to='account.orderitem'),
        ),
    ]
